import { useState } from "react";

import {
  FileDown,
  FileText,
  Database,
  Table2,
  Download,
  ShieldCheck,
  User,
  Clock3,
  Network,
  Brain,
} from "lucide-react";

const reportSections = [
  {
    title: "Actor Profile",
    description: "Identity, aliases and known handles",
    icon: User,
  },
  {
    title: "Relationship Graph",
    description: "Connected entities and infrastructure",
    icon: Network,
  },
  {
    title: "Investigation Timeline",
    description: "Important activity and events",
    icon: Clock3,
  },
  {
    title: "AI Attribution",
    description: "Confidence score and supporting evidence",
    icon: Brain,
  },
];

function Export() {
  const [loadingFormat, setLoadingFormat] = useState<string | null>(null);

  const handleExport = (format: string) => {
    setLoadingFormat(format);

    setTimeout(() => {
      if (format === "CSV") {
        const csvContent =
          "Actor,Identifier,Type,Risk,Confidence\n" +
          "ShadowFox,shadowfox7x3.onion,Onion Address,High,96%\n" +
          "DarkSpecter,0x83F...91A2,Wallet,Medium,82%\n" +
          "PhantomX,A9F3...7B21,PGP Key,Low,61%";

        const blob = new Blob([csvContent], {
          type: "text/csv;charset=utf-8;",
        });

        const url = URL.createObjectURL(blob);
        const link = document.createElement("a");

        link.href = url;
        link.download = "TraceX-Investigation.csv";
        link.click();

        URL.revokeObjectURL(url);
      }

      if (format === "JSON") {
        const data = {
          caseId: "TRACEX-INV-2025-0047",
          actor: "ShadowFox",
          confidence: "96%",
          entities: 7,
          events: 7,
          risk: "High",
        };

        const blob = new Blob([JSON.stringify(data, null, 2)], {
          type: "application/json",
        });

        const url = URL.createObjectURL(blob);
        const link = document.createElement("a");

        link.href = url;
        link.download = "TraceX-Investigation.json";
        link.click();

        URL.revokeObjectURL(url);
      }

      if (format === "Report") {
        const reportContent = `
TRACEX THREAT INTELLIGENCE INVESTIGATION

ShadowFox Attribution Report

Case ID: TRACEX-INV-2025-0047

Threat Actor: ShadowFox

Attribution: 96%

Assessment: Very High

Executive Summary:

The investigation identified multiple connected digital identities,
cryptographic indicators, wallet activity and infrastructure associated
with the investigated persona.

Behavioural and identity signals produced a high-confidence
attribution assessment.

Generated by TraceX
Trace • Connect • Attribute
`;

        const blob = new Blob([reportContent], {
          type: "text/plain;charset=utf-8;",
        });

        const url = URL.createObjectURL(blob);
        const link = document.createElement("a");

        link.href = url;
        link.download = "TraceX-ShadowFox-Investigation-Report.txt";
        link.click();

        URL.revokeObjectURL(url);
      }

      setLoadingFormat(null);
    }, 1000);
  };

  return (
    <div className="space-y-8">
      {/* Header */}
      <div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between">
        <div>
          <p className="text-sm font-medium uppercase tracking-wider text-blue-400">
            INVESTIGATION / OUTPUT
          </p>

          <h1 className="mt-2 text-3xl font-semibold text-white">
            Export Investigation
          </h1>

          <p className="mt-2 max-w-2xl text-sm text-slate-400">
            Generate structured investigation data and analyst-ready reports
            for further analysis or evidence review.
          </p>
        </div>

        <div className="flex items-center gap-2 rounded-lg border border-slate-800 bg-slate-900 px-4 py-2.5">
          <ShieldCheck size={17} className="text-emerald-400" />

          <span className="text-sm text-slate-300">
            Investigation Ready
          </span>
        </div>
      </div>

      {/* Case Summary */}
      <div className="rounded-xl border border-slate-800 bg-slate-900 p-6">
        <div className="flex flex-col gap-5 md:flex-row md:items-center md:justify-between">
          <div>
            <p className="text-xs font-medium uppercase tracking-wider text-slate-600">
              Investigation Case
            </p>

            <h2 className="mt-2 text-xl font-semibold text-white">
              ShadowFox Investigation
            </h2>

            <p className="mt-1 text-sm text-slate-500">
              Case ID: TRACEX-INV-2025-0047
            </p>
          </div>

          <div className="grid grid-cols-3 gap-6">
            <CaseStat label="Entities" value="7" />
            <CaseStat label="Events" value="7" />
            <CaseStat label="Confidence" value="96%" />
          </div>
        </div>
      </div>

      {/* Export Options */}
      <div>
        <div className="mb-5">
          <h2 className="text-lg font-semibold text-white">
            Export Formats
          </h2>

          <p className="mt-1 text-sm text-slate-500">
            Choose how you want to export the investigation data.
          </p>
        </div>

        <div className="grid gap-5 md:grid-cols-3">
          <ExportCard
            icon={Table2}
            title="CSV Data"
            description="Export investigation entities, indicators and events as a spreadsheet-compatible CSV file."
            format="CSV"
            buttonText="Export CSV"
            onClick={() => handleExport("CSV")}
            loading={loadingFormat === "CSV"}
          />

          <ExportCard
            icon={Database}
            title="JSON Data"
            description="Export structured investigation data for integration with other systems and analysis tools."
            format="JSON"
            buttonText="Export JSON"
            onClick={() => handleExport("JSON")}
            loading={loadingFormat === "JSON"}
          />

          <ExportCard
            icon={FileText}
            title="Investigation Report"
            description="Generate a complete analyst-ready report containing findings, relationships and AI analysis."
            format="REPORT"
            buttonText="Generate Report"
            onClick={() => handleExport("Report")}
            loading={loadingFormat === "Report"}
            featured
          />
        </div>
      </div>

      {/* Report Contents */}
      <div className="rounded-xl border border-slate-800 bg-slate-900 p-6">
        <div className="flex items-center gap-3">
          <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-blue-500/10 text-blue-400">
            <FileDown size={20} />
          </div>

          <div>
            <h2 className="text-lg font-semibold text-white">
              Report Contents
            </h2>

            <p className="text-sm text-slate-500">
              The investigation report will include the following sections.
            </p>
          </div>
        </div>

        <div className="mt-6 grid gap-3 md:grid-cols-2">
          {reportSections.map((section) => {
            const Icon = section.icon;

            return (
              <div
                key={section.title}
                className="flex items-center gap-4 rounded-lg border border-slate-800 bg-slate-950 p-4"
              >
                <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-slate-900 text-slate-400">
                  <Icon size={18} />
                </div>

                <div>
                  <p className="text-sm font-medium text-slate-300">
                    {section.title}
                  </p>

                  <p className="mt-1 text-xs text-slate-600">
                    {section.description}
                  </p>
                </div>
              </div>
            );
          })}
        </div>
      </div>

      {/* Export Preview */}
      <div className="rounded-xl border border-slate-800 bg-slate-950 p-6">
        <div className="flex flex-col gap-5 lg:flex-row lg:items-start lg:justify-between">
          <div>
            <div className="flex items-center gap-3">
              <FileText size={19} className="text-slate-400" />

              <h2 className="text-lg font-semibold text-white">
                Report Preview
              </h2>
            </div>

            <p className="mt-2 text-sm text-slate-500">
              Preview of the generated investigation report.
            </p>
          </div>

          <button
            onClick={() => handleExport("Report")}
            disabled={loadingFormat === "Report"}
            className="flex items-center justify-center gap-2 rounded-lg bg-blue-600 px-5 py-2.5 text-sm font-medium text-white transition hover:bg-blue-500 disabled:cursor-not-allowed disabled:opacity-60"
          >
            <Download size={16} />

            {loadingFormat === "Report"
              ? "Generating..."
              : "Generate Report"}
          </button>
        </div>

        {/* Preview */}
        <div className="mt-6 rounded-lg border border-slate-800 bg-slate-900 p-6">
          <div className="border-b border-slate-800 pb-5">
            <p className="text-xs uppercase tracking-wider text-blue-400">
              TRACEX THREAT INTELLIGENCE INVESTIGATION
            </p>

            <h3 className="mt-2 text-xl font-semibold text-white">
              ShadowFox Attribution Report
            </h3>

            <p className="mt-1 text-xs text-slate-600">
              Case ID: TRACEX-INV-2025-0047
            </p>
          </div>

          <div className="grid gap-5 py-6 md:grid-cols-3">
            <ReportValue
              label="Threat Actor"
              value="ShadowFox"
            />

            <ReportValue
              label="Attribution"
              value="96%"
            />

            <ReportValue
              label="Assessment"
              value="Very High"
            />
          </div>

          <div className="border-t border-slate-800 pt-5">
            <p className="text-xs font-medium uppercase tracking-wider text-slate-600">
              Executive Summary
            </p>

            <p className="mt-3 max-w-4xl text-sm leading-7 text-slate-400">
              The investigation identified multiple connected digital
              identities, cryptographic indicators, wallet activity and
              infrastructure associated with the investigated persona.
              Behavioural and identity signals produced a high-confidence
              attribution assessment.
            </p>
          </div>
        </div>
      </div>

      {/* Security Notice */}
      <div className="rounded-xl border border-amber-500/20 bg-amber-500/5 p-5">
        <div className="flex items-start gap-4">
          <ShieldCheck
            size={19}
            className="mt-0.5 shrink-0 text-amber-400"
          />

          <div>
            <h3 className="text-sm font-semibold text-amber-300">
              Investigation Data Notice
            </h3>

            <p className="mt-1 text-sm leading-6 text-slate-500">
              Exported investigation data may contain sensitive intelligence.
              Store and share generated reports according to your
              organization's security and evidence-handling procedures.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}

/* Export Card */
function ExportCard({
  icon: Icon,
  title,
  description,
  format,
  buttonText,
  onClick,
  loading,
  featured = false,
}: {
  icon: typeof FileText;
  title: string;
  description: string;
  format: string;
  buttonText: string;
  onClick: () => void;
  loading: boolean;
  featured?: boolean;
}) {
  return (
    <div
      className={`rounded-xl border p-6 ${featured
        ? "border-blue-500/30 bg-blue-500/5"
        : "border-slate-800 bg-slate-900"
        }`}
    >
      <div className="flex items-center justify-between">
        <div
          className={`flex h-11 w-11 items-center justify-center rounded-lg ${featured
            ? "bg-blue-500/10 text-blue-400"
            : "bg-slate-800 text-slate-400"
            }`}
        >
          <Icon size={21} />
        </div>

        <span className="rounded-md border border-slate-800 bg-slate-950 px-2 py-1 text-[10px] font-semibold text-slate-500">
          {format}
        </span>
      </div>

      <h3 className="mt-5 text-base font-semibold text-white">
        {title}
      </h3>

      <p className="mt-2 min-h-[72px] text-sm leading-6 text-slate-500">
        {description}
      </p>

      <button
        onClick={onClick}
        disabled={loading}
        className={`mt-5 flex w-full items-center justify-center gap-2 rounded-lg px-4 py-2.5 text-sm font-medium transition ${featured
          ? "bg-blue-600 text-white hover:bg-blue-500"
          : "border border-slate-800 bg-slate-950 text-slate-300 hover:border-slate-700 hover:text-white"
          }`}
      >
        {loading ? (
          <>
            <span className="h-4 w-4 animate-spin rounded-full border-2 border-slate-400 border-t-transparent" />
            Generating...
          </>
        ) : (
          <>
            <Download size={16} />
            {buttonText}
          </>
        )}
      </button>
    </div>
  );
}

/* Case Stat */
function CaseStat({
  label,
  value,
}: {
  label: string;
  value: string;
}) {
  return (
    <div className="text-right">
      <p className="text-lg font-semibold text-white">
        {value}
      </p>

      <p className="mt-1 text-[11px] text-slate-600">
        {label}
      </p>
    </div>
  );
}

/* Report Value */
function ReportValue({
  label,
  value,
}: {
  label: string;
  value: string;
}) {
  return (
    <div>
      <p className="text-xs text-slate-600">
        {label}
      </p>

      <p className="mt-1 text-sm font-semibold text-slate-300">
        {value}
      </p>
    </div>
  );
}

export default Export;